[uwsgi]
chdir = /app
module = mysite.wsgi:application
master = true
processes = 4
threads = 2
http = 0.0.0.0:8997
vacuum = true
die-on-term = true
buffer-size = 32768
harakiri = 60
max-requests = 5000
