from .config import *
from .banner import *
from .image import *
# from .user import *
from .user import User as CustomUser
from .user_auths import *
from .user_attribute_rewards_log import *
from .user_level_config import *
from .user_asset import *
from .user_asset_detail import *
from .user_invite_record import *
from .user_withdraw_order import *
from .user_transfer_record import *
from .user_check_record import *
from .check_in_point import *
from .spot_level_config import *
from .spot_boost import *
from .spot_boost_config import *
from .spot_category import *
from .premium_order import *
from .sol_transaction import *
from .rpc_config import *
from .address_transaction import *
from .user_pay_record import *
from .check_in_point_image import *
from .verification_code import *
from .verification_code_order import *
from .user_image import *
from .product import *
from .product_image import *
from .user_like import *
from .check_in_point_advertisement import *
from .user_advertisement_claim_record import *
from .complaint import *
from .ota import *  
from .chat import *
from .shop_admin_eventconfig import *
from .payment_order import *
from .address_checkpoint import *
from .comment import *
from .product_tag_config import *
from .product_favorite import *
from .product_visit_history import *
from .address import *
from .product_order import *
from .product_refund import *
from .check_in import *
from .check_in_tag import *
from .check_in_comment import *
from .check_in_member import *
from .check_in_image import *
from .chenk_in_tag_relation import *
from .user_follow import *
from .check_in_like import *
from .user_stat import *
from .check_in_message import *
from .check_in_message_read_progress import *
from .check_in_member_config import *
from .checkin_member_order import *
from .check_in_comment_like import *
