# Generated by Django 4.1.2 on 2025-02-20 09:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='', max_length=200)),
                ('link_type', models.CharField(default='', max_length=20, verbose_name='external、inside、image、activity')),
                ('link_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='要跳转的外部url')),
                ('show_start_at', models.DateTimeField(blank=True, verbose_name='展示开始时间')),
                ('show_end_at', models.DateTimeField(blank=True, verbose_name='展示结束时间')),
                ('activity_short_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='CheckInPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('category', models.CharField(max_length=20, verbose_name='类别')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('amount', models.BigIntegerField()),
                ('value', models.CharField(default='', max_length=50)),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('landmark_image', models.CharField(max_length=255, verbose_name='地标图片')),
                ('country', models.CharField(max_length=50, verbose_name='国家')),
                ('region', models.CharField(max_length=50, verbose_name='省/地区')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('place_id', models.CharField(max_length=100, verbose_name='地点ID')),
                ('location', models.CharField(max_length=255, verbose_name='具体位置')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('total_checked_in', models.IntegerField(default=0, verbose_name='总签到次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'check_in_point',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.CharField(max_length=255, unique=True)),
                ('_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spot', 'Spot'), ('avatar', 'Avatar'), ('task', 'Task'), ('other', 'Other')], max_length=10)),
                ('remark', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('keep_source_name', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='SpotBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(verbose_name='上线时间')),
                ('end_time', models.DateTimeField(verbose_name='下线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spot_boost',
            },
        ),
        migrations.CreateModel(
            name='SpotBoostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(blank=True, choices=[('all', 'All'), ('all_official', 'All_official'), ('specified', 'Specified'), ('early_bird', 'Early_bird')], default='', max_length=20, null=True, verbose_name='all|specified')),
                ('spots', models.TextField(blank=True, default='', null=True, verbose_name='specified ids, 逗号分隔')),
                ('ratio', models.FloatField(default=0)),
                ('remark', models.CharField(default='', max_length=20, verbose_name='备注')),
                ('start_time', models.DateTimeField(verbose_name='上线时间')),
                ('end_time', models.DateTimeField(verbose_name='下线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spot_boost_config',
            },
        ),
        migrations.CreateModel(
            name='SpotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=20)),
                ('label', models.CharField(default='', max_length=20)),
                ('label_zh', models.CharField(default='', max_length=20, verbose_name='中文名')),
                ('label_zh_tw', models.CharField(default='', max_length=20, verbose_name='中文繁体名')),
                ('label_ru', models.CharField(default='', max_length=20, verbose_name='俄语名')),
                ('image_url', models.CharField(default='', max_length=400)),
                ('sort_index', models.IntegerField(default=0)),
                ('display', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spot_category',
            },
        ),
        migrations.CreateModel(
            name='SpotLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('experience', models.FloatField(default=0, verbose_name='经验值')),
                ('hash_rate', models.FloatField(default=0, verbose_name='算力')),
                ('stamina', models.FloatField(default=0, verbose_name='体力')),
                ('checkin_radius', models.IntegerField(default=0, verbose_name='签到半径')),
            ],
            options={
                'verbose_name': '地点等级配置',
                'verbose_name_plural': '地点等级配置',
                'db_table': 'spot_level_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('nickname', models.CharField(default='', max_length=50)),
                ('avatar_url', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(default=1, verbose_name='用户等级')),
                ('invite_code', models.CharField(max_length=50, verbose_name='邀请码')),
                ('hash_rate', models.FloatField(default=0, verbose_name='算力')),
                ('stamina', models.FloatField(default=0, verbose_name='体力')),
                ('available_signins', models.IntegerField(default=1)),
                ('is_premium', models.IntegerField(default=1)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('balance', models.FloatField(default=0, verbose_name='余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户资产',
                'verbose_name_plural': '用户资产',
                'db_table': 'user_asset',
            },
        ),
        migrations.CreateModel(
            name='UserAssetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('invited_id', models.BigIntegerField(blank=True, null=True, verbose_name='推荐人ID（推荐奖励）')),
                ('category', models.CharField(choices=[('move', '移动'), ('check_in', '签到'), ('event', '活动')], max_length=20, verbose_name='奖励类别')),
                ('related_id', models.BigIntegerField(verbose_name='相关ID（spot_id）')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('rewards', models.FloatField(default=0, verbose_name='奖励数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户资产明细',
                'verbose_name_plural': '用户资产明细',
                'db_table': 'user_asset_detail',
            },
        ),
        migrations.CreateModel(
            name='UserAttributeRewardsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('category', models.CharField(choices=[('hash_rate', '算力'), ('stamina', '体力'), ('sign_in', '签到')], max_length=20, verbose_name='奖励类别')),
                ('label', models.CharField(default='user_upgrade、buy_premium...', max_length=50, verbose_name='标签')),
                ('rewards', models.FloatField(default=0, verbose_name='奖励数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户属性奖励记录',
                'verbose_name_plural': '用户属性奖励记录',
                'db_table': 'user_attribute_rewards_log',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='第三方提供者')),
                ('external_id', models.CharField(max_length=100, verbose_name='外部用户 ID')),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='钱包地址')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_auths',
            },
        ),
        migrations.CreateModel(
            name='UserCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('point_id', models.BigIntegerField(verbose_name='打开点id')),
                ('day', models.CharField(max_length=10, verbose_name='打卡日期 YYYYMMDD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_check_record',
            },
        ),
        migrations.CreateModel(
            name='UserInviteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_id', models.BigIntegerField(verbose_name='邀请人')),
                ('invitee_id', models.BigIntegerField(verbose_name='被邀请人')),
                ('day', models.IntegerField(verbose_name='日期(年月日)')),
                ('rewards', models.FloatField(default=0, verbose_name='奖励数值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_invite_record',
            },
        ),
        migrations.CreateModel(
            name='UserLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(unique=True, verbose_name='等级ID')),
                ('hash_rate', models.FloatField(default=0, verbose_name='算力')),
                ('stamina', models.FloatField(default=0, verbose_name='体力')),
                ('available_signins', models.IntegerField(default=1, verbose_name='可签到次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户等级配置',
                'verbose_name_plural': '用户等级配置',
                'db_table': 'user_level_config',
            },
        ),
        migrations.CreateModel(
            name='UserPremiumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name='币种代码')),
                ('amount', models.BigIntegerField()),
                ('value', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20, verbose_name='订单价值')),
                ('wallet_pay_address', models.CharField(max_length=255, verbose_name='钱包支付地址')),
                ('order_status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户高级订单',
                'verbose_name_plural': '用户高级订单',
                'db_table': 'user_premium_order',
            },
        ),
        migrations.CreateModel(
            name='UserTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField()),
                ('sender_name', models.CharField(max_length=100)),
                ('receive_id', models.BigIntegerField()),
                ('receive_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_transfer_record',
            },
        ),
        migrations.CreateModel(
            name='UserWithdrawOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('withdraw_status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('in_review', 'InReview'), ('success', 'Success'), ('refuse', 'Refuse')], default='unclaimed', max_length=20)),
                ('currency', models.CharField(default='', max_length=20)),
                ('amount', models.BigIntegerField()),
                ('value', models.CharField(default='', max_length=50)),
                ('withdraw_wallet_address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('withdraw_tx_hash', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('withdraw_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_withdraw_order',
            },
        ),
        migrations.AddIndex(
            model_name='userwithdraworder',
            index=models.Index(fields=['user_id'], name='z_user_with_user_id_d0f6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='usercheckrecord',
            index=models.Index(fields=['user_id', 'day'], name='z_user_chec_user_id_933392_idx'),
        ),
        migrations.AddField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auths', to='supermap.user'),
        ),
        migrations.AddIndex(
            model_name='userattributerewardslog',
            index=models.Index(fields=['user_id'], name='idx_user_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_id'),
        ),
        migrations.AddField(
            model_name='spotboost',
            name='boost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.spotboostconfig'),
        ),
        migrations.AddField(
            model_name='spotboost',
            name='spot_id',
            field=models.ForeignKey(db_column='spot_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='supermap.checkinpoint'),
        ),
        migrations.AddConstraint(
            model_name='userauth',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
        migrations.AddIndex(
            model_name='spotboost',
            index=models.Index(fields=['spot_id'], name='z_spot_boos_spot_id_9dd8d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spotboost',
            unique_together={('boost', 'spot_id')},
        ),

        migrations.RunSQL(
            sql="""
ALTER TABLE `user` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE banner 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE check_in_point 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE config 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE spot_boost 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE spot_boost_config 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE spot_category 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_asset 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_asset_detail 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_attribute_rewards_log 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_auths 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_check_record 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_invite_record 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_level_config 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_premium_order 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_transfer_record 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE user_withdraw_order 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
