# Generated by Django 4.1.2 on 2025-02-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spotboost',
            new_name='spot_boost_spot_id_ecd3ac_idx',
            old_name='z_spot_boos_spot_id_9dd8d3_idx',
        ),
        migrations.RenameIndex(
            model_name='usercheckrecord',
            new_name='user_check__user_id_68eca6_idx',
            old_name='z_user_chec_user_id_933392_idx',
        ),
        migrations.RenameIndex(
            model_name='userwithdraworder',
            new_name='user_withdr_user_id_770285_idx',
            old_name='z_user_with_user_id_d0f6d5_idx',
        ),
        migrations.AddField(
            model_name='userlevelconfig',
            name='checkin_limit',
            field=models.IntegerField(default=1, verbose_name='可打卡次数'),
        ),
    ]
