# Generated by Django 4.1.2 on 2025-02-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0002_rename_z_spot_boos_spot_id_9dd8d3_idx_spot_boost_spot_id_ecd3ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='status',
            field=models.IntegerField(default=0, verbose_name='是否展示'),
        ),
    ]
