# Generated by Django 4.1.2 on 2025-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0003_checkinpoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='hash_rate',
            field=models.FloatField(default=0, verbose_name='算力'),
        ),
    ]
