# Generated by Django 4.1.2 on 2025-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0004_checkinpoint_hash_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
    ]
