# Generated by Django 4.1.2 on 2025-02-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0005_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinpoint',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='checkinpoint',
            name='value',
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
    ]
