# Generated by Django 4.1.2 on 2025-02-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0006_remove_checkinpoint_amount_remove_checkinpoint_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassetdetail',
            name='invited_id',
        ),
        migrations.AddField(
            model_name='userassetdetail',
            name='invitee_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='被邀请人ID'),
        ),
    ]
