# Generated by Django 4.1.2 on 2025-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0007_remove_userassetdetail_invited_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('err_msg', models.CharField(blank=True, max_length=50, null=True)),
                ('order_finished', models.BooleanField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
                ('sol_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ton_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'premium_order',
            },
        ),
    ]
