# Generated by Django 4.1.2 on 2025-02-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0008_premiumorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPremiumOrder',
        ),
    ]
