# Generated by Django 4.1.2 on 2025-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0009_delete_userpremiumorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=50, verbose_name='from address')),
                ('to_address', models.CharField(max_length=50, verbose_name='to address')),
                ('lt', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('value', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('currency', models.CharField(default='', max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('token_address', models.CharField(max_length=50, verbose_name='token address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_checked', models.BooleanField(default=False)),
                ('need_check', models.BooleanField(default=True)),
                ('pay_type', models.CharField(default='', max_length=20)),
                ('instruction_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sol_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='soltransaction',
            index=models.Index(fields=['hash'], name='sol_transac_hash_7556f8_idx'),
        ),
        migrations.AddIndex(
            model_name='soltransaction',
            index=models.Index(fields=['lt'], name='sol_transac_lt_649eb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soltransaction',
            unique_together={('hash', 'lt', 'from_address', 'to_address', 'instruction_index')},
        ),
    ]
