# Generated by Django 4.1.2 on 2025-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0010_soltransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpcConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=20, verbose_name='type:sol|ton')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RPC配置',
                'verbose_name_plural': 'RPC配置',
                'db_table': 'rpc_config',
            },
        ),
    ]
