# Generated by Django 4.1.2 on 2025-02-26 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0011_rpcconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66)),
                ('from_address', models.CharField(max_length=50, verbose_name='from address')),
                ('to_address', models.CharField(max_length=50, verbose_name='to address')),
                ('lt', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('currency', models.CharField(default='', max_length=20)),
                ('comment', models.CharField(default='', max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('pay_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_type', models.CharField(default='', max_length=20)),
                ('need_check', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'address_transaction',
            },
        ),
        migrations.CreateModel(
            name='UserPayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('wallet_address', models.CharField(max_length=50, verbose_name='用户钱包地址')),
                ('transaction_status', models.IntegerField(default=0, verbose_name='0-未完成 1-已完成')),
                ('transaction_amount', models.FloatField()),
                ('lt', models.BigIntegerField()),
                ('transaction_hash', models.CharField(max_length=64)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_pay_record',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='moved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlevelconfig',
            name='stamina_reward',
            field=models.BigIntegerField(default=0, verbose_name='每秒运动的奖励'),
        ),
        migrations.AddIndex(
            model_name='userpayrecord',
            index=models.Index(fields=['user_id'], name='user_pay_re_user_id_baf0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='addresstransaction',
            index=models.Index(fields=['hash'], name='address_tra_hash_6e6bd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addresstransaction',
            unique_together={('hash', 'from_address', 'to_address')},
        ),
    ]
