# Generated by Django 4.1.2 on 2025-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0012_addresstransaction_userpayrecord_user_moved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_stamina',
            field=models.FloatField(default=0, verbose_name='剩余体力'),
        ),
    ]
