# Generated by Django 4.1.2 on 2025-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0013_user_remaining_stamina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remaining_stamina',
            field=models.IntegerField(default=0, verbose_name='剩余体力'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stamina',
            field=models.IntegerField(default=0, verbose_name='体力'),
        ),
    ]
