# Generated by Django 4.1.2 on 2025-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0014_alter_user_remaining_stamina_alter_user_stamina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevelconfig',
            name='stamina',
            field=models.IntegerField(default=0, verbose_name='体力'),
        ),
    ]
