# Generated by Django 4.1.2 on 2025-02-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0015_alter_userlevelconfig_stamina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevelconfig',
            name='available_signins',
        ),
        migrations.RunSQL(
            sql="""
ALTER TABLE `user` 
    MODIFY COLUMN moved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
""",
        ),
    ]
