# Generated by Django 4.1.2 on 2025-02-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0016_remove_userlevelconfig_available_signins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auths', to='supermap.user', to_field='user_id'),
        ),
    ]
