# Generated by Django 4.1.2 on 2025-02-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0017_alter_userauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlevelconfig',
            name='stamina',
        ),
    ]
