# Generated by Django 4.1.2 on 2025-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0019_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='owner_id',
            field=models.BigIntegerField(default=0, verbose_name='owner_id'),
        ),
    ]
