# Generated by Django 4.1.2 on 2025-03-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0020_checkinpoint_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
