# Generated by Django 4.1.2 on 2025-03-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0021_checkinpoint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInPointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片地址')),
                ('sort_index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('check_in_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supermap.checkinpoint', verbose_name='关联地标')),
            ],
            options={
                'verbose_name': '地标图片',
                'verbose_name_plural': '地标图片',
                'db_table': 'check_in_point_image',
                'ordering': ['sort_index', '-created_at'],
            },
        ),
    ]
