# Generated by Django 4.1.2 on 2025-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0022_checkinpointimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0, verbose_name='金额')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('check_code_num', models.IntegerField(default=0, verbose_name='验证码数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('status', models.IntegerField(default=1, verbose_name='状态(0:不展示,1:展示)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('spot_id', models.BigIntegerField()),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=0, verbose_name='鉴黄审核状态(0:未审核,1:审核通过,2:审核不通过)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_image',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_uid', models.BigIntegerField()),
                ('code', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0, verbose_name='状态(0:未使用,1:已使用)')),
                ('order_id', models.BigIntegerField(verbose_name='订单id')),
                ('use_uid', models.BigIntegerField(verbose_name='使用人id')),
                ('use_time', models.DateTimeField(verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verification_code',
            },
        ),
        migrations.CreateModel(
            name='VerificationCodeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(default='', max_length=100)),
                ('code_num', models.IntegerField(default=0, verbose_name='验证码数量')),
                ('amount', models.FloatField(default=0, verbose_name='金额')),
                ('pay_type', models.CharField(default='EFC', max_length=20, verbose_name='支付方式(EFC:EFC)')),
                ('status', models.IntegerField(default=0, verbose_name='支付状态(0:未支付,1:已支付,2:已取消)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verification_code_order',
            },
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='verification_code',
            field=models.CharField(default='', max_length=32, verbose_name='核销码'),
        ),
        # migrations.AddConstraint(
        #     model_name='verificationcodeorder',
        #     constraint=models.Index(fields=['user_id', 'product_id'], name='idx_user_product'),
        # ),
        migrations.AddConstraint(
            model_name='verificationcode',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code'),
        ),
        migrations.AddConstraint(
            model_name='userimage',
            constraint=models.Index(fields=['user_id', 'spot_id'], name='idx_user_spot'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.Index(fields=['product_id'], name='idx_product_id'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_id',), name='unique_product_id'),
        ),
    ]
