# Generated by Django 4.1.2 on 2025-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0023_product_productimage_userimage_verificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodeorder',
            name='ue_order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
