# Generated by Django 4.1.2 on 2025-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0024_verificationcodeorder_ue_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='status',
            field=models.CharField(max_length=20, verbose_name='状态(UNUSE:未使用,USED:已使用)'),
        ),
    ]
