# Generated by Django 4.1.2 on 2025-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0026_remove_product_unique_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodeorder',
            name='status',
            field=models.CharField(default='UNPAY', max_length=20, verbose_name='支付状态(UNPAY:未支付,PAYED:已支付,CANCEL:已取消)'),
        ),
    ]
