# Generated by Django 4.1.2 on 2025-03-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0027_alter_verificationcodeorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('spot_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_like',
            },
        ),
        migrations.AddConstraint(
            model_name='userlike',
            constraint=models.UniqueConstraint(fields=('user_id', 'spot_id'), name='idx_user_id_spot_id'),
        ),
        migrations.RunSQL(
            sql="""
ALTER TABLE `user_like` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
