# Generated by Django 4.1.2 on 2025-03-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0028_userlike_userlike_idx_user_id_spot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.IntegerField(choices=[(1, '普通会员'), (2, '高级会员'), (3, 'VIP会员'), (4, '至尊会员')], default=1, verbose_name='产品级别'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_tag',
            field=models.IntegerField(default=0, verbose_name='身份标签'),
        ),
    ]
