# Generated by Django 4.1.2 on 2025-03-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0029_product_level_user_identity_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level_tag',
            field=models.CharField(default='', max_length=50, verbose_name='级别标签'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_name',
            field=models.CharField(default='', max_length=50, verbose_name='身份标签'),
        ),
    ]
