# Generated by Django 4.1.2 on 2025-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0030_product_level_tag_user_identity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='激活状态'),
        ),
    ]
