# Generated by Django 4.1.2 on 2025-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0031_checkinpoint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodeorder',
            name='unit',
            field=models.CharField(default='USD', max_length=20, verbose_name='单位(USD:USD)'),
        ),
    ]
