# Generated by Django 4.1.2 on 2025-04-01 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0032_verificationcodeorder_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinpoint',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0.000000'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0.000000'), max_digits=12, null=True),
        ),
    ]
