# Generated by Django 4.1.2 on 2025-04-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0033_alter_checkinpoint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
