# Generated by Django 4.1.2 on 2025-04-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0034_alter_verificationcode_use_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='external_url',
            field=models.CharField(default='', max_length=100, verbose_name='外部链接'),
        ),
    ]
