# Generated by Django 4.1.2 on 2025-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0035_checkinpoint_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='audit_status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
    ]
