# Generated by Django 4.1.2 on 2025-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0036_checkinpoint_audit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='official', max_length=20, verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='product',
            name='check_in_point_id',
            field=models.BigIntegerField(default=0, verbose_name='地标ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255, verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.FloatField(default=0, verbose_name='原价'),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE check_in_point ALTER COLUMN audit_status SET DEFAULT 0;'
        ),
    ]
