# Generated by Django 4.1.2 on 2025-04-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0037_product_category_product_check_in_point_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInPointAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='广告标题')),
                ('description', models.TextField(verbose_name='广告描述')),
                ('reward_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='奖励金额')),
                ('reward_currency', models.CharField(default='USDT', max_length=20, verbose_name='奖励单位')),
                ('image_url', models.CharField(default='', max_length=255, verbose_name='广告图片')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='广告开始时间')),
                ('end_time', models.DateTimeField(verbose_name='广告结束时间')),
                ('check_in_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='supermap.checkinpoint', verbose_name='关联地标')),
            ],
            options={
                'verbose_name': '地标广告',
                'db_table': 'check_in_point_advertisement',
            },
        ),
        migrations.AddIndex(
            model_name='checkinpointadvertisement',
            index=models.Index(fields=['check_in_point_id'], name='idx_adv_check_point_id'),
        ),
          migrations.RunSQL(
            sql="""
ALTER TABLE `check_in_point_advertisement` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
