# Generated by Django 4.1.2 on 2025-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0038_checkinpointadvertisement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdvertisementClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('advertisement_id', models.BigIntegerField(verbose_name='广告ID')),
                ('reward_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='奖励金额')),
                ('reward_currency', models.CharField(default='FEC', max_length=20, verbose_name='奖励单位')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户广告领取记录',
                'db_table': 'user_advertisement_claim_record',
            },
        ),
        migrations.AddIndex(
            model_name='useradvertisementclaimrecord',
            index=models.Index(fields=['user_id', 'advertisement_id'], name='idx_user_adv_id'),
        ),
          migrations.RunSQL(
            sql="""
ALTER TABLE `user_advertisement_claim_record` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
