# Generated by Django 4.1.2 on 2025-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0039_useradvertisementclaimrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info_error', '地标信息有误(如名称，描述，图片)'), ('illegal_content', '地标内容涉及违法违规内容'), ('other_issues', '地标有其他问题，我要举报')], max_length=20, verbose_name='投诉类型')),
                ('check_in_point_id', models.BigIntegerField(verbose_name='打卡点ID')),
                ('user_id', models.BigIntegerField(verbose_name='投诉用户ID')),
                ('description', models.TextField(verbose_name='投诉描述')),
                ('images', models.TextField(blank=True, null=True, verbose_name='投诉图片')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投诉',
                'verbose_name_plural': '投诉',
                'db_table': 'complaint',
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user_id'], name='complaint_user_id_ce855c_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['check_in_point_id'], name='complaint_check_i_15c461_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaint_status_e7f8cc_idx'),
        ),
          migrations.RunSQL(
            sql="""
ALTER TABLE `complaint` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
