# Generated by Django 4.1.2 on 2025-04-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0040_complaint_complaint_complaint_user_id_ce855c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodeorder',
            name='order_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
