# Generated by Django 4.1.2 on 2025-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0041_verificationcodeorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_currency',
            field=models.CharField(default='FEC', max_length=20, verbose_name='单位'),
        ),
    ]
