# Generated by Django 4.1.2 on 2025-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0042_product_amount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='telegram_url',
            field=models.CharField(default='', max_length=100, verbose_name='telegram'),
        ),
    ]
