# Generated by Django 4.1.2 on 2025-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0043_checkinpoint_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithdraworder',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='userwithdraworder',
            constraint=models.UniqueConstraint(fields=('order_id',), name='unique_order_id'),
        ),
    ]
