# Generated by Django 4.1.2 on 2025-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0044_userwithdraworder_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithdraworder',
            name='withdraw_status',
            field=models.CharField(choices=[('in_review', 'InReview'), ('success', 'Success'), ('refuse', 'Refuse')], default='unclaimed', max_length=20),
        ),
    ]
