# Generated by Django 4.1.2 on 2025-05-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0045_alter_userwithdraworder_withdraw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20, verbose_name='平台')),
                ('force_update', models.CharField(choices=[('force', '强制更新'), ('optional', '可选更新')], default='optional', max_length=20, verbose_name='更新类型')),
                ('download_url', models.CharField(max_length=255, verbose_name='下载地址')),
                ('release_notes', models.TextField(verbose_name='更新说明')),
                ('min_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='最低支持版本')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('md5', models.CharField(blank=True, max_length=32, null=True, verbose_name='文件MD5')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'APP版本更新',
                'verbose_name_plural': 'APP版本更新',
                'db_table': 'ota',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ota',
            index=models.Index(fields=['platform', 'version'], name='ota_platfor_888802_idx'),
        ),
        migrations.AddIndex(
            model_name='ota',
            index=models.Index(fields=['is_active'], name='ota_is_acti_b98db2_idx'),
        ),
         migrations.RunSQL(
            sql="""
ALTER TABLE `ota` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
