# Generated by Django 4.1.2 on 2025-05-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0046_ota_ota_ota_platfor_888802_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ota',
            name='platform',
            field=models.CharField(choices=[('ios.cn', 'iOS-国内'), ('ios.global', 'iOS-海外'), ('android.cn', 'Android-国内'), ('android.global', 'Android-海外')], max_length=20, verbose_name='平台'),
        ),
    ]
