# Generated by Django 4.1.2 on 2025-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0047_alter_ota_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='description_cn',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述-中文'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述-英文'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='title_cn',
            field=models.CharField(default='', max_length=255, verbose_name='标题-中文'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='标题-英文'),
        ),
    ]
