# Generated by Django 4.1.2 on 2025-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0048_checkinpoint_description_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='believe_url',
            field=models.CharField(default='', max_length=150, verbose_name='believe'),
        ),
    ]
