# Generated by Django 4.1.2 on 2025-05-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0049_checkinpoint_believe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='small', max_length=10, verbose_name='图片类型(small:小图,large:大图)'),
        ),
    ]
