# Generated by Django 4.1.2 on 2025-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0050_productimage_image_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkinpoint',
            index=models.Index(fields=['status', 'is_active', 'audit_status', 'latitude', 'longitude'], name='idx_check_in_point_search'),
        ),
    ]
