# Generated by Django 4.1.2 on 2025-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0051_checkinpoint_idx_check_in_point_search'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkinpoint',
            name='idx_check_in_point_search',
        ),
        migrations.AddIndex(
            model_name='checkinpoint',
            index=models.Index(fields=['status', 'is_active', 'audit_status'], name='idx_check_in_point_status'),
        ),
        migrations.AddIndex(
            model_name='checkinpoint',
            index=models.Index(fields=['latitude'], name='idx_check_in_point_latitude'),
        ),
    ]
