# Generated by Django 4.1.2 on 2025-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0053_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='tokens',
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
