# Generated by Django 4.1.2 on 2025-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0054_remove_conversation_tokens_message_user_id'),
    ]

    operations = [
        # 先删除外键约束
        migrations.RunSQL(
            "ALTER TABLE chat_message DROP FOREIGN KEY chat_message_conversation_id_a1207bf4_fk_chat_conversation_id;",
            "ALTER TABLE chat_message ADD CONSTRAINT chat_message_conversation_id_a1207bf4_fk_chat_conversation_id FOREIGN KEY (conversation_id) REFERENCES chat_conversation(id);"
        ),
        # 修改字符集
        migrations.RunSQL(
            "ALTER TABLE chat_conversation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "ALTER TABLE chat_conversation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE chat_message CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "ALTER TABLE chat_message CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        # 重新添加外键约束
        migrations.RunSQL(
            "ALTER TABLE chat_message ADD CONSTRAINT chat_message_conversation_id_a1207bf4_fk_chat_conversation_id FOREIGN KEY (conversation_id) REFERENCES chat_conversation(id);",
            "ALTER TABLE chat_message DROP FOREIGN KEY chat_message_conversation_id_a1207bf4_fk_chat_conversation_id;"
        ),
    ]
