# Generated by Django 4.1.2 on 2025-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0055_set_charset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
