# Generated by Django 4.1.2 on 2025-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0056_remove_conversation_user_conversation_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConfig',
            fields=[
                ('conversation_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '聊天配置',
                'verbose_name_plural': '聊天配置',
                'db_table': 'chat_config',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.RunSQL(
            sql="""
ALTER TABLE `chat_config` 
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
""",
        ),
    ]
