# Generated by Django 4.1.2 on 2025-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0057_chatconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconfig',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
