# Generated by Django 4.1.2 on 2025-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0058_alter_chatconfig_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='pcn_url',
            field=models.CharField(default='', max_length=150, verbose_name='pcn url'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='whatsapp_url',
            field=models.CharField(default='', max_length=150, verbose_name='whatsapp url'),
        ),
    ]
