# Generated by Django 4.1.2 on 2025-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0059_checkinpoint_pcn_url_checkinpoint_whatsapp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('chain', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('last_check_block', models.BigIntegerField()),
                ('last_check_time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('error_count', models.IntegerField()),
                ('last_error', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('metadata', models.JSONField()),
                ('contract_address', models.CharField(max_length=42)),
                ('token_decimals', models.IntegerField()),
            ],
            options={
                'db_table': 'address_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('chain', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('from_address', models.CharField(blank=True, max_length=42, null=True)),
                ('to_address', models.CharField(max_length=42)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('metadata', models.JSONField()),
                ('tx_data', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_order_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_callback', models.BooleanField()),
            ],
            options={
                'db_table': 'payment_orders',
            },
        ),
        migrations.CreateModel(
            name='ShopAdminEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=20)),
                ('signature', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('scan_speed', models.IntegerField()),
                ('create_block', models.BigIntegerField()),
                ('scan_block', models.BigIntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'shop_admin_eventconfig',
                'unique_together': {('contract', 'signature')},
            },
        ),
    ]
