# Generated by Django 4.1.2 on 2025-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0060_addresscheckpoint_paymentorder_shopadmineventconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('expired', '已过期'), ('refunded', '已退款')], default='pending', max_length=20),
        ),
    ]
