# Generated by Django 4.1.2 on 2025-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0061_alter_paymentorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodeorder',
            name='status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('cancel', '已取消')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)'),
        ),
    ]
