# Generated by Django 4.1.2 on 2025-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0062_alter_verificationcodeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_usd',
            field=models.FloatField(default=0, verbose_name='金额(USD)'),
        ),
    ]
