# Generated by Django 4.1.2 on 2025-07-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0063_product_amount_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresscheckpoint',
            options={'verbose_name': '支付方式列表', 'verbose_name_plural': '支付方式列表'},
        ),
        migrations.AlterModelOptions(
            name='paymentorder',
            options={'verbose_name': '支付订单列表', 'verbose_name_plural': '支付订单列表'},
        ),
        migrations.AlterModelOptions(
            name='shopadmineventconfig',
            options={'verbose_name': 'event配置', 'verbose_name_plural': 'event配置'},
        ),
    ]
