# Generated by Django 4.1.2 on 2025-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0064_alter_addresscheckpoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcodeorder',
            name='product_num',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AddField(
            model_name='verificationcodeorder',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='verificationcodeorder',
            name='amount',
            field=models.FloatField(default=0, verbose_name='总金额'),
        ),
    ]
