# Generated by Django 4.1.2 on 2025-08-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0065_verificationcodeorder_product_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='believe_id',
            field=models.CharField(default='', max_length=150, verbose_name='believe_id'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='wechat',
            field=models.CharField(default='', max_length=150, verbose_name='wechat'),
        ),
    ]
