# Generated by Django 4.1.2 on 2025-08-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0065_verificationcodeorder_product_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='like_count',
            field=models.BigIntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='product',
            name='visited',
            field=models.BigIntegerField(default=0, verbose_name='用户浏览过'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=0, verbose_name='FEC金额'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255, verbose_name='产品图片, 废弃'),
        ),
    ]
