# Generated by Django 4.1.2 on 2025-08-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0066_checkinpoint_believe_id_checkinpoint_wechat'),
        ('supermap', '0066_checkinpoint_like_count_product_tags_product_visited_and_more'),
    ]

    operations = [
    ]
