# Generated by Django 4.1.2 on 2025-08-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0067_merge_20250820_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='visited',
            new_name='visited_count',
        ),
    ]
