# Generated by Django 4.1.2 on 2025-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0068_rename_visited_product_visited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='comment_count',
            field=models.BigIntegerField(default=0, verbose_name='用户浏览过'),
        ),
        migrations.AddField(
            model_name='product',
            name='comment_count',
            field=models.BigIntegerField(default=0, verbose_name='用户浏览过'),
        ),
    ]
