# Generated by Django 4.1.2 on 2025-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0069_checkinpoint_comment_count_product_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.BigIntegerField(default=0, verbose_name='地标ID')),
                ('product_id', models.BigIntegerField(default=0, verbose_name='product ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='地标ID')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
