# Generated by Django 4.1.2 on 2025-08-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0070_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_count',
            field=models.BigIntegerField(default=0, verbose_name='收藏数量'),
        ),
    ]
