# Generated by Django 4.1.2 on 2025-08-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0071_product_favorite_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=20, unique=True)),
                ('sort_index', models.IntegerField(default=0)),
                ('mark', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_tag_config',
            },
        ),
    ]
