# Generated by Django 4.1.2 on 2025-08-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0072_producttagconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audit_status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
    ]
