# Generated by Django 4.1.2 on 2025-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0073_product_audit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=True)),
                ('product_id', models.BigIntegerField(default=True)),
                ('mark', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_favorite',
            },
        ),
        migrations.AddIndex(
            model_name='productfavorite',
            index=models.Index(fields=['user_id'], name='product_fav_user_id_a0ceb3_idx'),
        ),
        migrations.AddIndex(
            model_name='productfavorite',
            index=models.Index(fields=['product_id'], name='product_fav_product_72bfab_idx'),
        ),
        migrations.AddConstraint(
            model_name='productfavorite',
            constraint=models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_constraint_user_product'),
        ),
    ]
