# Generated by Django 4.1.2 on 2025-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0074_productfavorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('product_id', models.BigIntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_visit_history',
            },
        ),
        migrations.AddIndex(
            model_name='productvisithistory',
            index=models.Index(fields=['user_id'], name='product_vis_user_id_5915d8_idx'),
        ),
        migrations.AddIndex(
            model_name='productvisithistory',
            index=models.Index(fields=['product_id'], name='product_vis_product_7b8a26_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvisithistory',
            constraint=models.UniqueConstraint(fields=('user_id', 'product_id'), name='unique_constraint_user_product_history'),
        ),
    ]
