# Generated by Django 4.1.2 on 2025-08-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0075_productvisithistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_active',
            field=models.IntegerField(default=False, verbose_name='上架状态'),
        ),
    ]
