# Generated by Django 4.1.2 on 2025-08-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0076_product_in_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
