# Generated by Django 4.1.2 on 2025-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0077_rename_in_active_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.IntegerField(default=True, verbose_name='上架状态'),
        ),
    ]
