# Generated by Django 4.1.2 on 2025-08-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0078_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='上架状态'),
        ),
    ]
