# Generated by Django 4.1.2 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0079_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态(1:pending:2:rejected)'),
        ),
    ]
