# Generated by Django 4.1.2 on 2025-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0080_alter_productimage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttagconfig',
            old_name='tag',
            new_name='tag_cn',
        ),
        migrations.AddField(
            model_name='producttagconfig',
            name='tag_en',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态(0:pending;1:approved;2:rejected)'),
        ),
    ]
