# Generated by Django 4.1.2 on 2025-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0081_rename_tag_producttagconfig_tag_cn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttagconfig',
            name='tag_cn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttagconfig',
            name='tag_en',
            field=models.CharField(default='', max_length=20),
        ),
    ]
