# Generated by Django 4.1.2 on 2025-09-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0082_alter_producttagconfig_tag_cn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinpoint',
            name='believe_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='believe_id'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='believe_url',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='believe'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='external_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='外部链接'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='landmark_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地标图片'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='具体位置'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='pcn_url',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='pcn url'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地点ID'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省/地区'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='telegram_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='核销码'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='wechat',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='wechat'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='whatsapp_url',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='whatsapp url'),
        ),
    ]
