# Generated by Django 4.1.2 on 2025-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0083_alter_checkinpoint_believe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audit_status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.BigIntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
