# Generated by Django 4.1.2 on 2025-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0084_comment_audit_status_alter_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='用户ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('area', models.TextField(max_length=50)),
                ('detail', models.TextField(max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
