# Generated by Django 4.1.2 on 2025-09-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0086_address_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='start',
        ),
    ]
