# Generated by Django 4.1.2 on 2025-09-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0087_remove_address_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='start',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='start',
            field=models.IntegerField(default=5),
        ),
    ]
