# Generated by Django 4.1.2 on 2025-09-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0088_address_start_comment_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='start',
            new_name='star',
        ),
    ]
