# Generated by Django 4.1.2 on 2025-09-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0089_rename_start_address_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='start',
            new_name='star',
        ),
        migrations.RemoveField(
            model_name='address',
            name='star',
        ),
    ]
