# Generated by Django 4.1.2 on 2025-09-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0090_rename_start_comment_star_remove_address_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='is_default',
        ),
    ]
