# Generated by Django 4.1.2 on 2025-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0091_rename_default_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
