# Generated by Django 4.1.2 on 2025-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0092_comment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(default=0)),
                ('spot_id', models.BigIntegerField(default=0)),
                ('ue_order_id', models.CharField(default='', max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('amount', models.FloatField(default=0, verbose_name='总金额')),
                ('product_price', models.FloatField(default=0, verbose_name='商品单价')),
                ('pay_type', models.CharField(default='FEC', max_length=20, verbose_name='支付方式(FEC:FEC)')),
                ('unit', models.CharField(default='USD', max_length=20, verbose_name='单位(USD:USD)')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', '待支付'), ('PENDING_SHIPMENT', '已支付'), ('PENDING_RECEIPT', '已取消'), ('COMPLETED', '交易完成'), ('CANCELLED', '已取消'), ('REFUND_IN_PROGRESS', '退款中'), ('REFUNDED', '已经退款')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)')),
                ('is_commented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_order',
            },
        ),
        migrations.AlterField(
            model_name='verificationcodeorder',
            name='pay_type',
            field=models.CharField(default='FEC', max_length=20, verbose_name='支付方式(FEC:FEC)'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['user_id', 'product_id'], name='product_ord_user_id_de4272_idx'),
        ),
    ]
