# Generated by Django 4.1.2 on 2025-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0093_productorder_alter_verificationcodeorder_pay_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('pending_shipment', '已支付'), ('pending_receipt', '待收货'), ('completed', '交易完成'), ('cancelled', '已取消'), ('refund_in_progress', '退款中'), ('refunded', '已经退款')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)'),
        ),
    ]
