# Generated by Django 4.1.2 on 2025-09-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0094_productorder_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='cancel_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productorder',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
