# Generated by Django 4.1.2 on 2025-09-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0095_productorder_cancel_by_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField()),
                ('amount', models.FloatField(default=0, verbose_name='总金额')),
                ('unit', models.CharField(default='USD', max_length=20, verbose_name='单位(USD:USD)')),
                ('status', models.CharField(choices=[('pending_approve', '待审核'), ('refunding', '退款中'), ('refunded', '已退款'), ('refund_failed', '退款失败')], default='pending_approve', max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_refund',
            },
        ),
    ]
