# Generated by Django 4.1.2 on 2025-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0096_productrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='cancel_at',
            field=models.BooleanField(default=0),
        ),
    ]
