# Generated by Django 4.1.2 on 2025-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0097_productorder_cancel_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='cancel_at',
            field=models.BigIntegerField(default=0),
        ),
    ]
