# Generated by Django 4.1.2 on 2025-09-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0098_alter_productorder_cancel_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='order_id',
            field=models.BigIntegerField(default=0, verbose_name='order ID'),
        ),
    ]
