# Generated by Django 4.1.2 on 2025-09-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0099_remove_comment_product_id_comment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_id',
            field=models.BigIntegerField(default=0, verbose_name='product ID'),
        ),
    ]
