# Generated by Django 4.1.2 on 2025-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0100_comment_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='seller_id',
            field=models.BigIntegerField(default=0, verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='user_id',
            field=models.BigIntegerField(verbose_name='买家'),
        ),
    ]
