# Generated by Django 4.1.2 on 2025-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0101_productorder_seller_id_alter_productorder_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='biz_type',
            field=models.CharField(choices=[('code', '核销码'), ('product', '产品')], default='code', max_length=20),
        ),
    ]
