# Generated by Django 4.1.2 on 2025-09-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0102_paymentorder_biz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='deleted_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
