# Generated by Django 4.1.2 on 2025-09-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0103_productorder_deleted_at_productorder_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productorder',
            name='refunded_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('pending_shipment', '已支付'), ('pending_receipt', '待收货'), ('completed', '交易完成'), ('cancelled', '已取消')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)'),
        ),
        migrations.AlterField(
            model_name='productrefund',
            name='status',
            field=models.CharField(choices=[('refunding', '退款中'), ('refunded', '已退款'), ('refund_rejected', '已拒绝')], default='refunding', max_length=20),
        ),
    ]
