# Generated by Django 4.1.2 on 2025-09-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0104_productorder_is_refunded_productorder_refunded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='is_refunded',
        ),
        migrations.AddField(
            model_name='productorder',
            name='refund_status',
            field=models.CharField(choices=[('refunding', '退款中'), ('refunded', '已退款'), ('refund_rejected', '已拒绝')], default='refunding', max_length=20),
        ),
    ]
