# Generated by Django 4.1.2 on 2025-09-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0105_remove_productorder_is_refunded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='refunded_at',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='refund_status',
            field=models.CharField(choices=[('no_refund', '无退款'), ('refunding', '退款中'), ('refunded', '已退款'), ('refund_rejected', '已拒绝')], default='no_refund', max_length=20),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('pending_shipment', '已支付'), ('pending_receipt', '待收货'), ('completed', '交易完成'), ('cancelled', '已取消'), ('closed', '已关闭')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)'),
        ),
    ]
