# Generated by Django 4.1.2 on 2025-09-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0106_remove_productorder_refunded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassetdetail',
            name='category',
            field=models.CharField(choices=[('move', '移动'), ('check_in', '签到'), ('event', '活动'), ('refund', '签到')], max_length=20, verbose_name='奖励类别'),
        ),
    ]
