# Generated by Django 4.1.2 on 2025-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0107_alter_userassetdetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待支付'), ('payment_processing', '支付处理中'), ('pending_shipment', '已支付'), ('pending_receipt', '待收货'), ('completed', '交易完成'), ('cancelled', '已取消'), ('closed', '已关闭')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)'),
        ),
    ]
