# Generated by Django 4.1.2 on 2025-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0108_alter_productorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='userassetdetail',
            name='rewards',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='奖励数值'),
        ),
    ]
