# Generated by Django 4.1.2 on 2025-09-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0109_alter_userasset_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='userassetdetail',
            name='rewards',
            field=models.FloatField(default=0, verbose_name='奖励数值'),
        ),
    ]
