# Generated by Django 4.1.2 on 2025-09-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0110_alter_userasset_balance_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='verificationcodeorder',
        #     name='idx_user_product',
        # ),
    ]
