# Generated by Django 4.1.2 on 2025-10-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0111_remove_verificationcodeorder_idx_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='user_id')),
                ('content', models.TextField(default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected'), (3, 'hidden')], default=0)),
                ('private', models.BooleanField(default=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.checkinpoint', verbose_name='关联地标')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='user_id')),
                ('check_in_tag_id', models.BigIntegerField(default=0, verbose_name='check_in_tag_id')),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.checkin', verbose_name='关联打卡')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片地址')),
                ('sort_index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.checkin', verbose_name='关联打卡')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, default=0, null=True)),
                ('reply_to_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'normal'), (1, 'hidden'), (2, 'deleted')], default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.checkin', verbose_name='关联打卡')),
            ],
        ),
    ]
