# Generated by Django 4.1.2 on 2025-10-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0112_checkin_checkinmember_checkintag_checkintagrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='longitude',
        ),
    ]
