# Generated by Django 4.1.2 on 2025-10-13 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0113_remove_checkin_address_remove_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkintagrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkintagrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
