# Generated by Django 4.1.2 on 2025-10-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0114_checkintagrelation_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkintagrelation',
            name='user_id',
        ),
    ]
