# Generated by Django 4.1.2 on 2025-10-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0115_remove_checkintagrelation_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('followed_user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
