# Generated by Django 4.1.2 on 2025-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0116_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincomment',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='followed_user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
