# Generated by Django 4.1.2 on 2025-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0117_alter_checkincomment_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpoint',
            name='checkin_comment_count',
            field=models.BigIntegerField(default=0, verbose_name='打开评论数量'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='checkin_count',
            field=models.BigIntegerField(default=0, verbose_name='打卡数量'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='checkin_like_count',
            field=models.BigIntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='checkinpoint',
            name='visit_count',
            field=models.BigIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='checkinpoint',
            name='comment_count',
            field=models.BigIntegerField(default=0, verbose_name='用户评论数量'),
        ),
    ]
