# Generated by Django 4.1.2 on 2025-10-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0118_checkinpoint_checkin_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincomment',
            name='city',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
