# Generated by Django 4.1.2 on 2025-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0119_checkincomment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincomment',
            name='reply_to_user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
