# Generated by Django 4.1.2 on 2025-10-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0120_checkincomment_reply_to_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='user_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermap.checkin', verbose_name='关联打卡')),
            ],
        ),
    ]
