# Generated by Django 4.1.2 on 2025-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0121_checkinlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
