# Generated by Django 4.1.2 on 2025-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0122_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('checkin_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
