# Generated by Django 4.1.2 on 2025-10-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0123_userstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkintag',
            name='reference_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
