# Generated by Django 4.1.2 on 2025-10-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0124_checkin_visit_count_checkintag_reference_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinpoint',
            old_name='visit_count',
            new_name='checkin_visit_count',
        ),
    ]
