# Generated by Django 4.1.2 on 2025-10-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0125_rename_visit_count_checkinpoint_checkin_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('other_user_id', models.BigIntegerField(default=0)),
                ('message_type', models.SmallIntegerField(choices=[(0, 'check_in_like'), (1, 'check_in_comment')], default=0)),
                ('check_in_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
