# Generated by Django 4.1.2 on 2025-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0127_checkinmessagereadprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmessage',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
