# Generated by Django 4.1.2 on 2025-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0128_checkinmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmessage',
            name='comment_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
