# Generated by Django 4.1.2 on 2025-10-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0129_checkinmessage_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmember',
            name='expired_timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkinmember',
            name='is_vip',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='checkinmember',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
