# Generated by Django 4.1.2 on 2025-10-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0130_checkinmember_expired_timestamp_checkinmember_is_vip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMemberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='', max_length=20)),
                ('fec_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('fec_origin_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('usdt_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('usdt_origin_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
