# Generated by Django 4.1.2 on 2025-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0131_checkinmemberconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmemberconfig',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
