# Generated by Django 4.1.2 on 2025-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0132_checkinmemberconfig_sort_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='biz_type',
            field=models.CharField(choices=[('code', '核销码'), ('product', '产品'), ('member', '会员')], default='code', max_length=20),
        ),
    ]
