# Generated by Django 4.1.2 on 2025-10-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0133_alter_paymentorder_biz_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMemberOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField(default=0)),
                ('ue_order_id', models.CharField(default='', max_length=100)),
                ('period', models.CharField(default='', max_length=20)),
                ('amount', models.FloatField(default=0, verbose_name='总金额')),
                ('product_price', models.FloatField(default=0, verbose_name='商品单价')),
                ('pay_type', models.CharField(default='FEC', max_length=20, verbose_name='支付方式(FEC:FEC)')),
                ('unit', models.CharField(default='USD', max_length=20, verbose_name='单位(USD:USD)')),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('paid', '支付处理中'), ('cancel', '已支付')], default='unpaid', max_length=20, verbose_name='支付状态(unpaid:未支付,paid:已支付,cancel:已取消)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member_order',
            },
        ),
        migrations.AddIndex(
            model_name='checkinmemberorder',
            index=models.Index(fields=['user_id'], name='member_orde_user_id_f7c954_idx'),
        ),
    ]
