# Generated by Django 4.1.2 on 2025-10-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0134_checkinmemberorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmember',
            name='is_vip',
        ),
    ]
