# Generated by Django 4.1.2 on 2025-10-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0135_remove_checkinmember_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincomment',
            name='check_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkinimage',
            name='check_in',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkinlike',
            name='check_in',
            field=models.BigIntegerField(default=0),
        ),
    ]
