# Generated by Django 4.1.2 on 2025-10-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0136_alter_checkincomment_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkincomment',
            old_name='check_in',
            new_name='check_in_id',
        ),
        migrations.RenameField(
            model_name='checkinimage',
            old_name='check_in',
            new_name='check_in_id',
        ),
        migrations.RenameField(
            model_name='checkinlike',
            old_name='check_in',
            new_name='check_in_id',
        ),
    ]
