# Generated by Django 4.1.2 on 2025-10-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0137_rename_check_in_checkincomment_check_in_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkintagrelation',
            name='check_in',
        ),
        migrations.AddField(
            model_name='checkintagrelation',
            name='check_in_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
