# Generated by Django 4.1.2 on 2025-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0138_remove_checkintagrelation_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_id', models.BigIntegerField(default=0)),
                ('comment_id', models.BigIntegerField(default=0)),
                ('comment_user_id', models.BigIntegerField(default=0)),
                ('user_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
