# Generated by Django 4.1.2 on 2025-10-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermap', '0139_checkincommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmessage',
            name='message_type',
            field=models.SmallIntegerField(choices=[(0, 'check_in_like'), (1, 'check_in_comment'), (2, 'check_in_comment_like')], default=0),
        ),
    ]
