# Generated by Django 4.1.2 on 2025-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermap", "0142_alter_checkinmemberorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinmemberorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "待支付"),
                    ("payment_processing", "支付处理中"),
                    ("paid", "已经支付"),
                    ("cancel", "已取消"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="支付状态(unpaid:未支付,paid:已支付,cancel:已取消)",
            ),
        ),
    ]
