"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",") if os.getenv("ALLOWED_HOSTS") else []

DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'supermap.apps.ValidatorsConfig',
    'bootstrap3',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_apscheduler',
    'scheduler.apps.SchedulerConfig',
    'import_export',
    'storages',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django_otp.middleware.OTPMiddleware',  # Disabled for local dev
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'apis.util.api_time_middleware.ApiTimeMiddleware',
    'apis.util.exception_middleware.ExceptionMiddleware',
]
IMPORT_EXPORT_USE_TRANSACTIONS = True

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DATABASE_NAME", ""),
        'USER': os.getenv("DATABASE_USER", ""),
        'PASSWORD': os.getenv("DATABASE_PASSWORD", ""),
        'charset': 'utf8mb4',
        'HOST': os.getenv("DATABASE_HOST", "127.0.0.1"),
        'PORT': os.getenv("DATABASE_PORT", "3306"),
        'OPTIONS': {
            'ssl': {} if os.getenv("DATABASE_CA", "") == ''
            else {
                'ca': os.getenv("DATABASE_CA", ""),
                'key': os.getenv("DATABASE_KEY", ""),
                'cert': os.getenv("DATABASE_CERT", ""),
            },
            'charset': 'utf8mb4',
            'use_unicode': True,
        }
    }
}

CACHES = {
    'default': {
        'BACKEND': os.getenv('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.getenv('CACHE_LOCATION', 'uscene-backend-local'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR.parent.parent / "shared" / "static"
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-bootstrap3的设置
BOOTSTRAP3 = {
    'include_jquery': True,
}

JWT = {
    'SECRET_KEY': os.getenv("JWT_SECRET_KEY"),
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = os.getenv("EMAIL_PORT", "587")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# 收件人看到的发件人
EMAIL_FROM = os.getenv("EMAIL_FROM", "")
EMAIL_USE_TLS = True
EMAIL_SEND_ENABLE = True

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = os.getenv("CORS_ORIGIN_ALLOW_ALL", "False").lower() in ("true", "1")
CORS_ORIGIN_WHITELIST = os.getenv("CORS_ORIGIN_WHITELIST", "").split(",") if os.getenv("CORS_ORIGIN_WHITELIST") else []
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW',)
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'Pool-Id',
)

APP_CONFIG = [
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'supermap.auth.AwsV4SignAuth',
    )}

DING = {
    'endpoint': 'https://oapi.dingtalk.com/robot/send?access_token=',
    'secret_access_key': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY"),
    'enable': os.getenv("BACKEND_DING_ENABLE", "False").lower() in ("true", "1"),
    'secret_access_keys': {
        'daily_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_DAILY"),
        'hourly_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_HOURLY"),
        'notice_report': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_NOTICE"),
        'alarm': os.getenv("BACKEND_DING_SECRET_ACCESS_KEY_ALARM"),
    }
}

# lark配置
LARK = {
    'enable': os.getenv("BACKEND_LARK_ENABLE", "False").lower() in ("true", "1"),
    'endpoint': 'https://open.larksuite.com/open-apis/bot/v2/hook/',
    'secret_access_keys': {
        'daily_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_DAILY"),
        'hourly_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_HOURLY"),
        'notice_report': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_NOTICE"),
        'alarm': os.getenv("BACKEND_LARK_SECRET_ACCESS_KEY_ALARM"),
    }
}

TG = {
    "TOKEN_TEST": os.getenv("BACKEND_TG_BOT_TOKEN_TEST"),
    "TOKEN_PRD": os.getenv("BACKEND_TG_BOT_TOKEN_PRD")
}

# AWS credentials (used by AwsV4SignAuth in supermap/auth.py and apis/util/auth.py)
AWS = {
    'access_key': os.getenv("AWS_ACCESS_KEY", ""),
    'secret_access_key': os.getenv("AWS_SECRET_ACCESS_KEY", ""),
}

AWS_KEY = {
    'access_key': os.getenv("AWS_ACCESS_KEY", ""),
    'secret_access_key': os.getenv("AWS_SECRET_ACCESS_KEY", ""),
}

# Solana RPC
SOL_RPC = os.getenv("SOL_RPC", "https://api.mainnet-beta.solana.com")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': './info.log',
            'formatter': 'verbose'
        },
    },
    'root': {
        'handlers': os.getenv("LOGGING_HANDLERS", "console").split(","),
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': os.getenv("LOGGING_HANDLERS", "console").split(","),
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
